### ISSUE TITLE
Extract Logger to separate file

### ISSUE THREAD

**Issue by devdszerszen** [kaemo/RecipeFinder#1]
https://github.com/kaemo/RecipeFinder/blob/12f488361752e4461a69b0ce2fd71b4357f76eae/app/src/main/java/pl/kaemo/recipefinder/ui/mainActivity/MainActivity.kt#L116

Suggested target: ui/util

**Comment by kaemo** [comment]
done in commit d15af65777738df02b825f5124e490c701535d19
