### ISSUE TITLE
Change to Logger.logMessage

### ISSUE THREAD

**Issue by devdszerszen** [kaemo/RecipeFinder#2]
https://github.com/kaemo/RecipeFinder/blob/12f488361752e4461a69b0ce2fd71b4357f76eae/app/src/main/java/pl/kaemo/recipefinder/ui/mainActivity/MainActivity.kt#L110

**Comment by kaemo** [comment]
done in commit f6c622fb005e4a2b07e792f76dcb65b98fb8784b
