### ISSUE TITLE
Invert logic to be driven by VM

### ISSUE THREAD

**Issue by devdszerszen** [kaemo/RecipeFinder#4]
https://github.com/kaemo/RecipeFinder/blob/12f488361752e4461a69b0ce2fd71b4357f76eae/app/src/main/java/pl/kaemo/recipefinder/ui/recipesListActivity/RecipesListActivity.kt#L36

**Comment by kaemo** [comment]
done in commit 9f269843d2b23b7ff4300df3c354d5fccdff1a71
